- nmcli:
    conn_name: eth0
    type: ethernet
    dns4:
      - 10.90.201.100
    state: present

- name: YUM update
  command: yum -y update
  tags:
    - pkgupdate

- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result
  tags:
    - epel
 
- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  when: not epel_repofile_result.stat.exists
  tags:
    - epel
 
- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  tags:
    - epel

- hostname:
    name: "{{ hostname }}"

- name: update hosts
  template: src=hosts.j2 dest=/etc/hosts backup=yes owner=root group=root mode=0644
  tags: hosts

- name: be sure ntp is installed
  yum: name=ntp state=installed
  tags: ntp

- name: be sure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: be sure ntpd is running and enabled
  service: name=ntpd state=started enabled=yes
  tags: ntp

