---
- debug: msg="host is {{ item }}"
  with_items:  "{{ groups['all'] }}" 

- name: Execute specific setup for each distribution
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}-setup.yml"
    - "{{ ansible_distribution }}-setup.yml"
    - "default-setup.yml"
  tags: setup


